import Head from "next/head";

import { Inter } from "next/font/google";
import styles from "/styles/Home.module.css";

import { useState } from "react";
import Link from "next/link";
import LoginFrom from "@/components/login/LoginForm";
 
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
 
  return (
    <div className={styles.main}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="tourist" content="nextjs,tourist guide" />
        <link rel="icon" href="/favcion.ico" />
      </Head>

      <LoginFrom/>
      
    </div>
  );
}
